version: 0.2

env:
    variables:
        GOOS: "linux"
        PACKAGE: "github.com/jakevc/awsEbTest"

phases:
    install:
        runtime-versions: 
            golang: 1.13
        commands:

            # link package to codebuild src dir 
            - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/handler"

            # Install golint
            - go get -u golang.org/x/lint/golint

            # install testify
            - go get -u github.com/stretchr/testify

    pre_build:
        commands:

          # Make sure we're in the project directory within our GOPATH
          - cd "/go/src/handler"

          # Fetch all dependencies
          - go get -t ./...

          # Ensure code passes all lint tests
          - golint -set_exit_status

          # Check the Go code for common problems with 'go vet'
          - go vet .

          # Run all tests included with our application
          - go test .


    build:
        commands: 
            
            # logs build 
            - echo Compiling go code..
            # AWS code deploy expects binary called app 
            - go build -o main
            # echo environment
            - ls /go/src/

    post_build:
        commands: 
            - echo Build complete on `date` 
artifacts:
    files: 
        - main 
        - buildspec.yml



