version: 0.2

env:
    variables:
        GOOS: "linux"
        PACKAGE: "github.com/jakevc/awsEbTest"

phases:
    install:
        runtime-versions: 
            golang: 1.13
        commands:

            # link package to codebuild src dir 
            - mkdir -p "/go/src/$(dirname ${PACKAGE})"
            - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 
            # Print all environment variables (handy for AWS CodeBuild logs)
            - env

            # Install golint
            - go get -u golang.org/x/lint/golint

    pre_build:
        commands:

          # Make sure we're in the project directory within our GOPATH
          - cd "/go/src/${PACKAGE}"

          # Fetch all dependencies
          - go get -t ./...

          # Ensure code passes all lint tests
          - golint -set_exit_status

          # Check the Go code for common problems with 'go vet'
          - go vet .

          # Run all tests included with our application
          - go test .


    build:
        commands: 
            
            # logs build 
            - echo Compiling go code..
            # AWS code deploy expects binary called app 
            - go build -o app main.go

    post_build:
        commands: 
            - echo Build complete on `date` 
artifacts:
    files: 
        - app 
        - buildspec.yml



