version: 0.02

env:
    variables:
        GOOS: "linux"
phases:
    install:
        commands:
            - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
            - echo GOPATH - $GOPATH
            - echo GOROOT - $GOROOT
            - echo Moving Packages...
            - cp -r ./vendor/* /go/src/
    build:
        commands: 
            - echo Build started on `date`
            - echo Compiling go code..
            - go build -o app main.go
    post_build:
        commands: 
            - echo Build complete on `date` 
artifacts:
    files: 
        - app
        - buildspec.yml



